import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsVocabulary: SidebarsConfig = {
    vocabularySidebar: [
        {
            type: 'category',
            label: 'Vocabulary',
            link: {
                type: "generated-index",
            },
            items: [
                {
                    'Minna': [{type: 'autogenerated',
                        dirName: 'vocabulary/minna',}]
                },
                {
                    'Kanji': [{type: 'autogenerated',
                        dirName: 'vocabulary/kanji',}]
                },
                {
                    'Topic Vocab': [{type: 'autogenerated',
                        dirName: 'vocabulary/topic',}]
                },
            ]
        },

    ]

};

export default sidebarsVocabulary;