import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsGrammar: SidebarsConfig =    {
    grammarSidebar: [
        {
            type: 'category',
            label: 'Grammar',
            link: {
                type: "generated-index",
            },
            items: [
                {
                    'Minna': [{type: 'autogenerated',
                        dirName: 'minna',}]
                },
                {
                    'Try': [{type: 'autogenerated',
                        dirName: 'try',}]
                },
            ]
        },

    ]
    }
;

export default sidebarsGrammar;